const express = require('express');
const router = express.Router();
const _ = require('underscore')
const helper = require('../helperModule/helper-module')
const Car = require('./some-module')

const movies = ['The Land Girls',
'The Interesteller',
'Avengers',
'The Spiderman',
'First Love, Last Rites',
'I Married a Strange Person',
'A Nightmare On Elm Street: The Dream Child',
"Freddy's Dead: The Final Nightmare",
"Wes Craven's New Nightmare",
'Airplane!',
'Repo Man',
'Rocket Singh: Salesman of the Year',
'Raise the Titanic',
'Restoration',
'The Return of the Living Dead',
'Rejsen til Saturn',
'Return to the Land of Wonders',
"Schindler's List",
'A Streetcar Named Desire',
'Shadow Conspiracy',
'Short Cut to Nirvana: Kumbh Mela',
'Spartacus',
'Sunday',
'She Done Him Wrong',
'Secret, The',
'Sea Rex 3D: Journey to a Prehistoric World',
'State Fair',
'Sticky Fingers of Time',
'Stargate - The Ark of Truth',
"She's Gotta Have It",
'Stargate',
'The Shadow',
'Show Boat',
'Shadowlands',
'Shanghai Surprise',
'Shalako',
'Sheena',
'Shine',
'The Shining',
'Haakon Haakonsen',
'Ishtar',
'Showgirls',
'The Shawshank Redemption',
'Silver Bullet',
'Side Effects',
'Set It Off',
'The Silence of the Lambs',
'Silver Medalist',
'Silent Trigger',
'Thinner',
'Sling Blade',
'Slacker',
'Some Like it Hot',
'The Scarlet Letter',
'Silmido',
'Sleeper',
'Sleepers',
'The Slaughter Rule',
'Solomon and Sheba',
'Sur Le Seuil',
'The Usual Suspects',
'Silverado',
'Salvador',
'Sex, Lies, and Videotape',
'Show Me',
'Simon',
'Super Mario Bros.',
'Somewhere in Time',
'Smoke Signals',
'Serial Mom',
'Sommersturm',
'Silent Movie',
'The Santa Clause',
'The Singles Ward',
'Sense and Sensibility',
"Singin' in the Rain",
'Solitude',
'The Sound of Music',
"She's the One",
'Straight out of Brooklyn',
'Spaceballs',
'Speed',
'Species',
'Sphinx',
'Spaced Invaders',
'Spellbound',
'Splash',
'Superman IV: The Quest for Peace',
'Superman II',
'Superman III',
'Sparkler',
'Superman',
'The Specialist',
'The Sorcerer',
'Sisters in Law',
"Smilla's Sense of Snow",
'Assassins',
'Star Trek: The Motion Picture',
'Star Trek III: The Search for Spock',
'Star Trek IV: The Voyage Home',
'Stand by Me',
'Stone Cold',
'The Stewardesses',
'Street Fighter',
'Star Trek II: The Wrath of Khan',
'Steal (Canadian Release)',
'The Sting',
'Stonewall',
'Star Trek V: The Final Frontier',
'Star Trek VI: The Undiscovered Country',
'Star Trek: Generations',
'Stripes',
'Striptease',
'Star Wars Ep. IV: A New Hope',
'Saints and Soldiers',
'Steppin: The Movie',
'Strangers on a Train',
'Sugar Hill',
'Stiff Upper Lips',
'Shichinin no samurai',
'Sweet Charity',
'Sands of Iwo Jima',
'The Spy Who Loved Me',
'The Swindle',
'Swingers',
'Snow White and the Seven Dwarfs',
'The Sweet Hereafter',
'She Wore a Yellow Ribbon',
'Sex with Strangers',
'Spy Hard',
'Shi Yue Wei Cheng',
'Tango',
'The Age of Innocence',
'Talk Radio',
'The Texas Chainsaw Massacre',
'The Texas Chainsaw Massacre 2',
'Timecop',
'Tin Cup',
'Torn Curtain',
'To Die For',
'Terror Train',
'Teen Wolf Too',
'The Fan',
'Timber Falls',
'Tae Guik Gi: The Brotherhood of War',
'The Incredibly True Adventure of Two Girls in Love',
'There Goes My Baby',
'Tank Girl',
'Top Gun',
'Thunderball',
'The Calling',
'The Craft',
'It Happened One Night',
'The Net',
'La otra conquista',
'The Journey',
'They Live',
'Tales from the Hood',
'Time Bandits',
'Tombstone',
'Time Changer',
'Teenage Mutant Ninja Turtles II: The Secret of the Ooze',
'Teenage Mutant Ninja Turtles III',
'Tango & Cash',
'Teenage Mutant Ninja Turtles',
'Topaz',
'Taps',
'Trainspotting',
'The Train',
'Troop Beverly Hills',
'Trekkies',
'True Lies',
'Terminator 2: Judgment Day',
'Travellers and Magicians',
'The Terminator',
'Tremors',
'True Romance',
'Tron',
'Trapeze',
'The Terrorist',
'Trois',
"Things to Do in Denver when You're Dead",
'A Time to Kill',
'Total Recall',
'This Thing of Ours',
'Tootsie',
'That Thing You Do!',
'The Trouble With Harry',
'Twins',
'Twister',
'Towering Inferno',
'Taxi Driver',
'Tycoon',
'Toy Story',
'Twilight Zone: The Movie',
'Unforgettable',
'UHF',
"Ulee's Gold",
'Under Siege 2: Dark Territory',
'The Untouchables',
'Under the Rainbow']

const films = [{'id': 1, 'name': 'The Land Girls'},
{'id': 2, 'name': 'First Love, Last Rites'},
{'id': 3, 'name': 'I Married a Strange Person'},
{'id': 4, 'name': "Let's Talk About Sex"},
{'id': 5, 'name': 'Slam'},
{'id': 6, 'name': 'Mississippi Mermaid'},
{'id': 7, 'name': 'Following'},
{'id': 8, 'name': 'Foolish'},
{'id': 9, 'name': 'Pirates'},
{'id': 10, 'name': 'Duel in the Sun'},
{'id': 11, 'name': 'Tom Jones'},
{'id': 12, 'name': 'Oliver!'},
{'id': 13, 'name': 'To Kill A Mockingbird'},
{'id': 14, 'name': 'Tora, Tora, Tora'},
{'id': 15, 'name': 'Hollywood Shuffle'},
{'id': 16, 'name': 'Over the Hill to the Poorhouse'},
{'id': 17, 'name': 'Wilson'},
{'id': 18, 'name': 'Darling Lili'},
{'id': 19, 'name': 'The Ten Commandments'},
{'id': 20, 'name': '12 Angry Men'},
{'id': 21, 'name': 'Twelve Monkeys'},
{'id': 22, 'name': 1776},
{'id': 23, 'name': 1941},
{'id': 24, 'name': 'Chacun sa nuit'},
{'id': 25, 'name': '2001: A Space Odyssey'},
{'id': 26, 'name': '20,000 Leagues Under the Sea'},
{'id': 27, 'name': '20,000 Leagues Under the Sea'},
{'id': 28, 'name': '24 7: Twenty Four Seven'},
{'id': 29, 'name': 'Twin Falls Idaho'},
{'id': 30, 'name': 'Three Kingdoms: Resurrection of the Dragon'},
{'id': 31, 'name': '3 Men and a Baby'},
{'id': 32, 'name': '3 Ninjas Kick Back'},
{'id': 33, 'name': 'Forty Shades of Blue'},
{'id': 34, 'name': '42nd Street'},
{'id': 35, 'name': 'Four Rooms'},
{'id': 36, 'name': 'The Four Seasons'},
{'id': 37, 'name': 'Four Weddings and a Funeral'},
{'id': 38, 'name': '51 Birch Street'},
{'id': 39, 'name': '55 Days at Peking'},
{'id': 40, 'name': 'Nine 1/2 Weeks'},
{'id': 41, 'name': 'AstÈrix aux Jeux Olympiques'},
{'id': 42, 'name': 'The Abyss'},
{'id': 43, 'name': 'Action Jackson'},
{'id': 44, 'name': 'Ace Ventura: Pet Detective'},
{'id': 45, 'name': 'Ace Ventura: When Nature Calls'},
{'id': 46, 'name': "April Fool's Day"},
{'id': 47, 'name': 'Among Giants'},
{'id': 48, 'name': 'Annie Get Your Gun'},
{'id': 49, 'name': 'Alice in Wonderland'},
{'id': 50, 'name': 'The Princess and the Cobbler'},
{'id': 51, 'name': 'The Alamo'},
{'id': 52, 'name': "Alexander's Ragtime Band"},
{'id': 53, 'name': 'Alive'},
{'id': 54, 'name': 'Amen'},
{'id': 55, 'name': 'American Graffiti'},
{'id': 56, 'name': 'American Ninja 2: The Confrontation'},
{'id': 57, 'name': 'The American President'},
{'id': 58, 'name': 'Annie Hall'},
{'id': 59, 'name': 'Anatomie'},
{'id': 60, 'name': 'The Adventures of Huck Finn'},
{'id': 61, 'name': 'The Apartment'},
{'id': 62, 'name': 'Apocalypse Now'},
{'id': 63, 'name': 'Arachnophobia'},
{'id': 64, 'name': 'Arn - Tempelriddaren'},
{'id': 65, 'name': 'Arnolds Park'},
{'id': 66, 'name': "Sweet Sweetback's Baad Asssss Song"},
{'id': 67, 'name': 'And Then Came Love'},
{'id': 68, 'name': 'Around the World in 80 Days'},
{'id': 69, 'name': 'Barbarella'},
{'id': 70, 'name': 'Barry Lyndon'},
{'id': 71, 'name': 'Barbarians, The'},
{'id': 72, 'name': 'Babe'},
{'id': 73, 'name': 'Boynton Beach Club'},
{'id': 74, 'name': "Baby's Day Out"},
{'id': 75, 'name': 'Bound by Honor'},
{'id': 76, 'name': 'Bon Cop, Bad Cop'},
{'id': 77, 'name': 'Back to the Future'},
{'id': 78, 'name': 'Back to the Future Part II'},
{'id': 79, 'name': 'Back to the Future Part III'},
{'id': 80, 'name': 'Butch Cassidy and the Sundance Kid'},
{'id': 81, 'name': 'Bad Boys'},
{'id': 82, 'name': 'Body Double'},
{'id': 83, 'name': 'The Beast from 20,000 Fathoms'},
{'id': 84, 'name': 'Beastmaster 2: Through the Portal of Time'},
{'id': 85, 'name': 'The Beastmaster'},
{'id': 86, 'name': 'Ben-Hur'},
{'id': 87, 'name': 'Ben-Hur'},
{'id': 88, 'name': 'Benji'},
{'id': 89, 'name': 'Before Sunrise'},
{'id': 90, 'name': 'Beauty and the Beast'},
{'id': 91, 'name': 'The Best Years of Our Lives'},
{'id': 92, 'name': 'The Ballad of Gregorio Cortez'},
{'id': 93, 'name': 'My Big Fat Independent Movie'},
{'id': 94, 'name': 'Battle for the Planet of the Apes'},
{'id': 95, 'name': 'Big Things'},
{'id': 96, 'name': 'Bogus'},
{'id': 97, 'name': 'Beverly Hills Cop'},
{'id': 98, 'name': 'Beverly Hills Cop II'},
{'id': 99, 'name': 'Beverly Hills Cop III'},
{'id': 100, 'name': 'The Black Hole'},
{'id': 101, 'name': 'Bathory'},
{'id': 102, 'name': 'Big'},
{'id': 103, 'name': 'The Big Parade'},
{'id': 104, 'name': 'Boyz n the Hood'},
{'id': 105, 'name': 'The Book of Mormon Movie, Volume 1: The Journey'},
{'id': 106, 'name': 'Return to the Blue Lagoon'},
{'id': 107, 'name': 'Bright Lights, Big City'},
{'id': 108, 'name': 'The Blue Bird'},
{'id': 109, 'name': 'The Blue Butterfly'},
{'id': 110, 'name': 'Blade Runner'},
{'id': 111, 'name': 'Bloodsport'},
{'id': 112, 'name': 'The Blues Brothers'},
{'id': 113, 'name': 'Blow Out'},
{'id': 114, 'name': "De battre mon coeur s'est arrÍtÈ"},
{'id': 115, 'name': 'The Broadway Melody'},
{'id': 116, 'name': 'Boom Town'},
{'id': 117, 'name': 'Bound'},
{'id': 118, 'name': 'Bang'},
{'id': 119, 'name': 'Bananas'},
{'id': 120, 'name': "Bill & Ted's Bogus Journey"},
{'id': 121, 'name': 'The Birth of a Nation'},
{'id': 122, 'name': 'The Ballad of Cable Hogue'},
{'id': 123, 'name': 'The Blood of Heroes'},
{'id': 124, 'name': 'The Blood of My Brother: A Story of Death in Iraq'},
{'id': 125, 'name': 'Boomerang'},
{'id': 126, 'name': 'The Bridge on the River Kwai'},
{'id': 127, 'name': 'Born on the Fourth of July'},
{'id': 128, 'name': 'Basquiat'},
{'id': 129, 'name': 'Black Rain'},
{'id': 130, 'name': 'Bottle Rocket'},
{'id': 131, 'name': 'Braindead'},
{'id': 132, 'name': 'The Bridges of Madison County'},
{'id': 133, 'name': 'The Brothers McMullen'},
{'id': 134, 'name': 'Dracula'},
{'id': 135, 'name': 'Broken Arrow'},
{'id': 136, 'name': 'Brainstorm'},
{'id': 137, 'name': 'Braveheart'},
{'id': 138, 'name': 'Les BronzÈs 3: amis pour la vie'},
{'id': 139, 'name': 'Brazil'},
{'id': 140, 'name': 'Blazing Saddles'},
{'id': 141, 'name': 'The Basket'},
{'id': 142, 'name': 'Bathing Beauty'},
{'id': 143, 'name': "Bill & Ted's Excellent Adventure"},
{'id': 144, 'name': 'A Bridge Too Far'},
{'id': 145, 'name': 'Beetle Juice'},
{'id': 146, 'name': 'Batman Returns'},
{'id': 147, 'name': 'Batman Forever'},
{'id': 148, 'name': 'Batman - The Movie'},
{'id': 149, 'name': 'Batman'},
{'id': 150, 'name': 'Buffy the Vampire Slayer'},
{'id': 151, 'name': "Bienvenue chez les Ch'tis"},
{'id': 152, 'name': 'Beyond the Valley of the Dolls'},
{'id': 153, 'name': 'Broken Vessels'},
{'id': 154, 'name': 'The Boys from Brazil'},
{'id': 155, 'name': 'The Business of Fancy Dancing'},
{'id': 156, 'name': 'Caddyshack'},
{'id': 157, 'name': 'Cape Fear'},
{'id': 158, 'name': 'Clear and Present Danger'},
{'id': 159, 'name': 'Carrie'},
{'id': 160, 'name': 'Casino Royale'},
{'id': 161, 'name': 'Camping Sauvage'},
{'id': 162, 'name': 'The Cotton Club'},
{'id': 163, 'name': 'Crop Circles: Quest for Truth'},
{'id': 164, 'name': 'Close Encounters of the Third Kind'},
{'id': 165, 'name': 'The Cable Guy'},
{'id': 166, 'name': 'Chocolate: Deep Dark Secrets'},
{'id': 167, 'name': "Child's Play"},
{'id': 168, 'name': "Child's Play 2"},
{'id': 169, 'name': 'Chain Reaction'},
{'id': 170, 'name': 'Charly'},
{'id': 171, 'name': 'Chariots of Fire'},
{'id': 172, 'name': 'A Christmas Story'},
{'id': 173, 'name': 'Cat on a Hot Tin Roof'},
{'id': 174, 'name': 'C.H.U.D.'},
{'id': 175, 'name': 'Charge of the Light Brigade, The'},
{'id': 176, 'name': 'Crooklyn'},
{'id': 177, 'name': 'Festen'},
{'id': 178, 'name': 'Cleopatra'},
{'id': 179, 'name': 'Cliffhanger'},
{'id': 180, 'name': 'The Californians'},
{'id': 181, 'name': 'The Client'},
{'id': 182, 'name': 'The Calling'},
{'id': 183, 'name': 'Clueless'},
{'id': 184, 'name': 'The Color Purple'},
{'id': 185, 'name': 'Clerks'},
{'id': 186, 'name': 'Central do Brasil'},
{'id': 187, 'name': 'Clash of the Titans'},
{'id': 188, 'name': 'Clockwatchers'},
{'id': 189, 'name': 'Commando'},
{'id': 190, 'name': 'The Color of Money'},
{'id': 191, 'name': 'Cinderella'},
{'id': 192, 'name': 'Congo'},
{'id': 193, 'name': 'Conan the Barbarian'},
{'id': 194, 'name': 'Conan the Destroyer'},
{'id': 195, 'name': 'Class of 1984'},
{'id': 196, 'name': 'The Clan of the Cave Bear'},
{'id': 197, 'name': 'The Case of the Grinning Cat'},
{'id': 198, 'name': 'Bacheha-Ye aseman'},
{'id': 199, 'name': 'Coming Home'},
{'id': 200, 'name': 'Nanjing! Nanjing!'}]



router.get('/test-me', function (req, res) {
    helper.printData('Hello Bro!! Wassup.')
    helper.greet('Shashikant Bharti')
    console.log('Today is', helper.today())
    let arr = [11,12,34,45,56,67,78,89,90]
    console.log(_.first(arr))
    console.log(_.first(arr, [3]))
    // car.setColor('Red')
    // console.log(car.getColor())
    // Car.greet();
    res.send('My first ever api!')
});

router.get('/test-you', function (req, res) {
    res.send('My first experiment!')
});

router.get('/movies', function (req, res) {
    res.send(movies)
});

router.get('/movies/:index', function (req, res) {
    let index = req.params.index
    if (index > movies.length - 1 || index < 0 || isNaN(index)){
        res.send(`Error: Invalid Index. Min index = 0 and Max index ${movies.length - 1}`)
    }
    res.send(movies[index])
});

router.get('/films', function (req, res) {
    res.send(films)
});

router.get('/films/:id', function (req, res) {
    let id = req.params.id
    if (id > movies.length - 1 || id < 0 || isNaN(id)){
        res.send(`Error: Invalid id. Min id = 1 and Max id ${movies.length - 1}`)
    }
    let film = films.find(x => x.id == id)
    res.send(film.name)
});

router.get('/profile/:name', (req, res) => {
    res.send(`This is ${req.params.name} profile.`)
})

router.get('/test', function (req, res) {
    res.send('Hello World!! I am node js. express js is most popular library.')
});

router.get('/sol1', (req, res) => {
    let n = 7
    let sum = n * (n + 1) / 2
    let numbers = [1,2,3,5,6,7]
    let missingNumber = sum - (numbers.reduce((total, x) => total + x, 0))
    
    res.send({data: missingNumber})

})

router.get('/sol2', (req, res) => {
    let numbers = [33, 34, 35, 37, 38]
    let n = numbers.length + 1
    let sum = (numbers[0] + numbers.at(-1)) * n / 2

    let missingNumber = sum - numbers.reduce((total, x) => total + x, 0)

    res.send({data: missingNumber})
})

module.exports = router;